apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: tiktaalick/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
              # In the container
            - mountPath: /app/story
              name: story-volume
      volumes:
          # On the host
        - name: story-volume
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: host-pvc